export const ADD_COCTAILS = "ADD_COCTAILS";
export const COCTAILS_LOADING = "COCTAILS_LOADING";
export const COCTAILS_ERROR = "COCTAILS_ERROR";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const ADD_COCTAIL = "ADD_COCTAIL";
export const COCTAIL_LOADING = "COCTAIL_LOADING";